// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBajreYn6xxZI5U9yRwGzzdnrgx669JgI8',
    appId: '1:318407072487:web:7a209b0d77a1db940ba042',
    messagingSenderId: '318407072487',
    projectId: 'gerenciadorcliente1',
    authDomain: 'gerenciadorcliente1.firebaseapp.com',
    storageBucket: 'gerenciadorcliente1.firebasestorage.app',
    measurementId: 'G-NTR8P2VJ6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP9myCPcJFOsI0rx_1jWsc0my4lKPOYzY',
    appId: '1:318407072487:android:906906cae53613ae0ba042',
    messagingSenderId: '318407072487',
    projectId: 'gerenciadorcliente1',
    storageBucket: 'gerenciadorcliente1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBisjIQrIgD5l0L7I2yLELRcwDLJrrMUJY',
    appId: '1:318407072487:ios:83f5e06f92c08c850ba042',
    messagingSenderId: '318407072487',
    projectId: 'gerenciadorcliente1',
    storageBucket: 'gerenciadorcliente1.firebasestorage.app',
    iosBundleId: 'com.example.gerenciadorClientes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBisjIQrIgD5l0L7I2yLELRcwDLJrrMUJY',
    appId: '1:318407072487:ios:83f5e06f92c08c850ba042',
    messagingSenderId: '318407072487',
    projectId: 'gerenciadorcliente1',
    storageBucket: 'gerenciadorcliente1.firebasestorage.app',
    iosBundleId: 'com.example.gerenciadorClientes',
  );
}
